// This file is automatically generated; see lib/Makefile
#ifdef _EXTRACT_SIGNALCONSTS
#define	SIGHUP	1	
#define	SIGINT	2	
#define	SIGQUIT	3	
#define	SIGILL	4	
#define	SIGTRAP	5	
#define	SIGABRT 6	
#define	SIGEMT	7	
#define	SIGFPE	8	
#define	SIGKILL	9	
#define	SIGBUS	10	
#define	SIGSEGV	11	
#define	SIGSYS	12	
#define	SIGPIPE	13	
#define	SIGALRM	14	
#define	SIGTERM	15	
#define	SIGURG	16	
#define	SIGSTOP	17	
#define	SIGTSTP	18	
#define	SIGCONT	19	
#define	SIGCHLD	20	
#define	SIGCLD	20	
#define	SIGTTIN	21	
#define	SIGTTOU	22	
#define	SIGIO	23	
#define	SIGPOLL	SIGIO	
#define	SIGXCPU	24	
#define	SIGXFSZ	25	
#define	SIGVTALRM 26	
#define	SIGPROF	27	
#define	SIGWINCH 28	
#define	SIGLOST 29	
#define	SIGUSR1 30	
#define	SIGUSR2 31	
#endif
#ifdef _EXTRACT_STDIOCONSTS
#define	FOPEN_MAX	20
#define FILENAME_MAX    __FILENAME_MAX__
#define	L_tmpnam	FILENAME_MAX
#define	TMP_MAX		26
#define	L_cuserid	9		
#define L_ctermid       16
#endif
