// This file is automatically generated; see lib/Makefile
#ifdef _EXTRACT_SIGNALCONSTS
#define	SIGHUP	1	
#define	SIGINT	2	
#define	SIGQUIT	3	
#define	SIGILL	4	
#define	SIGTRAP	5	
#define	SIGIOT	6	
#define	SIGABRT 6	
#define	SIGEMT	7	
#define	SIGFPE	8	
#define	SIGKILL	9	
#define	SIGBUS	10	
#define	SIGSEGV	11	
#define	SIGSYS	12	
#define	SIGPIPE	13	
#define	SIGALRM	14	
#define	SIGTERM	15	
#define	SIGUSR1	16	
#define	SIGUSR2	17	
#define	SIGCLD	18	
#define	SIGCHLD	18	
#define	SIGPWR	19	
#define	SIGWINCH 20	
#define	SIGURG	21	
#define	SIGPOLL 22	
#define	SIGIO	SIGPOLL	
#define	SIGSTOP 23	
#define	SIGTSTP 24	
#define	SIGCONT 25	
#define	SIGTTIN 26	
#define	SIGTTOU 27	
#define	SIGVTALRM 28	
#define	SIGPROF 29	
#define	SIGXCPU 30	
#define	SIGXFSZ 31	
#define	SIGWAITING 32	
#define	SIGLWP	33	
#define	SIGFREEZE 34	
#define	SIGTHAW 35	
#define	SIGCANCEL 36	
#define	SIGLOST	37	
#define	SIGSTKSZ	8192
#endif
#ifdef _EXTRACT_STDIOCONSTS
#define	FOPEN_MAX	_NFILE
#define	FILENAME_MAX    1024	
#define	TMP_MAX		17576	
#define	L_ctermid	9
#define	L_cuserid	9
#define	L_tmpnam	25	
#endif
