#!/bin/awk -f
	   { name=$1;
	     median=$3;
	     idx = match(name,"-");
	     noprint=0;
	     if (idx == 0)
	       type="cyc/";
	     else {
	       prefix=substr(name,1,idx);
	       if (prefix ~ "gcc")
	         type="c/";
	       else
	         noprint=1;
	       name=substr(name,idx+1);
	     }
	     if (!noprint) printf("%s %s %s\n",name,type,median); }
	     