#!/bin/awk -f
	   { name=$1;
	     median=$4;
	     idx = match(name,"-");
	     noprint=0;
	     if (idx == 0) {
	       noprint=1;
	     }
	     else {
	       prefix=substr(name,1,idx);
	       if (prefix ~ "gcc")
	         type="c/";
	       else
	         type="cyc/";
	       name=substr(name,idx+1);
	     }
	     if (!noprint) printf("%s %s %s\n",name,type,median); }
	     
