{ #include <stdio.h> }
nullable = "".
goo = "+".
; number = "3".
DIGIT = %d48-57.
number = 1*(DIGIT).
expr =  expr "+"{printf(" + ");} expr  | expr "*" expr | number$n {printf("%s",n);} | "{" number "}" {printf("{%s}",number);}.
; expr = [ nullable "bye" expr ].
start = "a "{printf("a ");} expr.

; number = "3".
; expr = expr "+" expr | number.
; start = "a " expr.
; DIGIT = %d48-57.
; number = 1*(DIGIT).
; LETTERA = "A".
; expr = expr "+" expr | expr "*" expr | number | "{" number$number "}" @repeat(number)LETTERA.
; start = "a " expr.
{
grammar_t parse_string(char ?s) {return NULL;}
}
