ASTRING-CHAR = ATOM-CHAR|resp-specials.
ATOM-CHAR = ((CHAR) - (atom-specials)).
CHAR = %d1-127.
CHAR8 = %d1-255.
CR = %d13.
CRLF = CR LF.
CTL = %d0-31|%d127.
DIGIT = %d48-57.
DQUOTE = %d34.
LF = %d10.
QUOTED-CHAR = (((TEXT-CHAR) - (quoted-specials)))|("\" quoted-specials).
SP = %d32.
TEXT-CHAR = ((CHAR) - (CR|LF)).
astring = 1*ASTRING-CHAR|string.
atom-specials = "("|")"|"{"|SP|CTL|resp-specials.
; (command CLOSE)
; (command (COPY 7 INBOX))
; (command (CREATE "foo"))
;command = tag SP (command-auth|command-select) CRLF.
command = tag SP (command-auth|command-select) SP.
command-auth = create.
command-select = "CLOSE"|copy.
copy = "COPY" SP sequence-set SP mailbox.
create = "CREATE" SP mailbox.
digit-nz = %d49-57.
mailbox = "INBOX"|astring.
number = 1*DIGIT.
nz-number = digit-nz *DIGIT.
quoted = DQUOTE *QUOTED-CHAR DQUOTE.
quoted-specials = DQUOTE|"\".
resp-specials = "]".
seq-number = nz-number|"*".
seq-range = seq-number ":" seq-number.
sequence-set = (seq-number|seq-range) *("," sequence-set).
string = quoted.
tag = 1*(((ASTRING-CHAR) - ("+"))).
; A CREATE foo
;
; B CLOSE
;
; C COPY *,100 bar
