#!/bin/bash
#
# usage: test-smlng <n>
#   where n is an integer, and the number of tests to perform

if [ $# != 1 ]; then
  echo "usage: $0 <n>"
  exit 1
fi

TMP=/tmp/smlng-test$$
TMP2=/tmp/smlng2-test$$

n=$1
i=1
while true; do
  ./generate > $TMP
  cat $TMP | ./smlng.exe > $TMP2
  ./validate.exe $TMP $TMP2
  if [ $? != 0 ]; then
    echo original is in $TMP
    echo processed is in $TMP2
    break
  fi
  i=$((i+1))
  if [ $i -gt $n ]; then
    break
  fi
done

#rm -f $TMP $TMP2