{.state = 132, .token = 363, .msg = "undeclared type or missing comma "},
{.state = 70, .token = 363, .msg = "type has not been declared "},
{.state = 494, .token = -1, .msg = "missing ';' "},
{.state = 320, .token = -1, .msg = "missing ')' on parameter list "},
{.state = 67, .token = -1, .msg = "expecting IDENTIFIER or '{' "},
{.state = 22, .token = -1, .msg = "expecting IDENTIFIER or '{' "},
{.state = 26, .token = -1, .msg = "expecting PATTERN "},
{.state = 28, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 29, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 37, .token = -1, .msg = "expecting '(' EXPRESSION ')' "},
{.state = 38, .token = -1, .msg = "expecting 'union' "},
{.state = 39, .token = -1, .msg = "expecting 'datatype' "},
{.state = 45, .token = -1, .msg = "expecting '((' ATTRIBUTE_LIST '))' "},
{.state = 48, .token = -1, .msg = "expecting '(' PARAMETER_LIST ')' "},
{.state = 116, .token = -1, .msg = "expecting KIND "},
{.state = 120, .token = -1, .msg = "expecting KIND "},
{.state = 56, .token = -1, .msg = "expecting ';' or '{' "},
{.state = 57, .token = -1, .msg = "expecting ';' or '{' "},
{.state = 33, .token = -1, .msg = "expecting '<' or IDENTIFIER "},
{.state = 866, .token = -1, .msg = "missing '};' "},
{.state = 69, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 96, .token = -1, .msg = "expecting '(' "},
{.state = 97, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 98, .token = -1, .msg = "expecting PATTERN "},
{.state = 232, .token = -1, .msg = "expecting IDENTIFIER or extra ',' "},
{.state = 122, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 128, .token = -1, .msg = "missing '}' "},
{.state = 269, .token = -1, .msg = "missing '}' "},
{.state = 132, .token = -1, .msg = "missing ';' "},
{.state = 272, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 271, .token = -1, .msg = "expecting DECLARATION "},
{.state = 145, .token = 0, .msg = "missing '}' "},
{.state = 152, .token = -1, .msg = "expecting ']' or EXPRESSION "},
{.state = 448, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 327, .token = -1, .msg = "expecting TYPE "},
{.state = 547, .token = -1, .msg = "missing ')' "},
{.state = 326, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 546, .token = -1, .msg = "missing ')' "},
{.state = 166, .token = -1, .msg = "expecting TYPE "},
{.state = 335, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 172, .token = -1, .msg = "missing '}' "},
{.state = 224, .token = -1, .msg = "expecting TYPE_VARIABLE or '_' "},
{.state = 173, .token = -1, .msg = "expecting '(' EXPRESSION ')' or '( TYPE ')' "},
{.state = 361, .token = -1, .msg = "missing ')' "},
{.state = 176, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 177, .token = -1, .msg = "expecting INITIALIZER or EXPRESSION "},
{.state = 178, .token = -1, .msg = "expecting '(' EXPRESSION ') "},
{.state = 347, .token = -1, .msg = "expecting EXPRESSION ') "},
{.state = 564, .token = -1, .msg = "missing ') "},
{.state = 179, .token = -1, .msg = "expecting '(' EXPRESSION ',' EXPRESSION ') "},
{.state = 348, .token = -1, .msg = "expecting EXPRESSION ',' EXPRESSION ') "},
{.state = 565, .token = -1, .msg = "expecting ',' EXPRESSION ') "},
{.state = 723, .token = -1, .msg = "missing ')' "},
{.state = 181, .token = -1, .msg = "expecting '(' "},
{.state = 350, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 567, .token = -1, .msg = "expecting ',' "},
{.state = 725, .token = -1, .msg = "expecting 'sizeof(' TYPE ')' "},
{.state = 922, .token = -1, .msg = "expecting TYPE "},
{.state = 1052, .token = -1, .msg = "missing ')' "},
{.state = 182, .token = -1, .msg = "expecting '(' "},
{.state = 351, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 568, .token = -1, .msg = "expecting ',' "},
{.state = 726, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 828, .token = -1, .msg = "expecting ',' "},
{.state = 923, .token = -1, .msg = "expecting 'sizeof' "},
{.state = 996, .token = -1, .msg = "expecting '(' "},
{.state = 1053, .token = -1, .msg = "expecting TYPE "},
{.state = 1072, .token = -1, .msg = "missing ')' "},
{.state = 183, .token = -1, .msg = "expecting '(' REGION_EXPRESSION ')' "},
{.state = 569, .token = -1, .msg = "missing ')' "},
{.state = 727, .token = -1, .msg = "expecting INITIALIZER or EXPRESSION "},
{.state = 185, .token = -1, .msg = "expecting '(' EXPRESSION ')' "},
{.state = 354, .token = -1, .msg = "expecting EXPRESSION ')' "},
{.state = 571, .token = -1, .msg = "missing ')' "},
{.state = 186, .token = -1, .msg = "expecting '(' TYPE ')' "},
{.state = 355, .token = -1, .msg = "expecting TYPE ')' "},
{.state = 572, .token = -1, .msg = "missing ')' "},
{.state = 187, .token = -1, .msg = "expecting '(' "},
{.state = 356, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 573, .token = -1, .msg = "expecting '.' IDENTIFIER or missing ')' "},
{.state = 732, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 519, .token = -1, .msg = "expecting TYPE_LIST, EXPRESSION_LIST, or ')' "},
{.state = 578, .token = -1, .msg = "expecting ')' "},
{.state = 582, .token = -1, .msg = "missing ':' EXPRESSION "},
{.state = 369, .token = -1, .msg = "missing EXPRESSION or extra '?' "},
{.state = 382, .token = -1, .msg = "missing EXPRESSION or extra '+' "},
{.state = 383, .token = -1, .msg = "missing EXPRESSION or extra '-' "},
{.state = 384, .token = -1, .msg = "missing EXPRESSION or extra '*' "},
{.state = 385, .token = -1, .msg = "missing EXPRESSION or extra '/' "},
{.state = 371, .token = -1, .msg = "missing EXPRESSION or extra '|' "},
{.state = 373, .token = -1, .msg = "missing EXPRESSION or extra '&' "},
{.state = 372, .token = -1, .msg = "missing EXPRESSION or extra '^' "},
{.state = 197, .token = -1, .msg = "missing EXPRESSION or extra '&' "},
{.state = 374, .token = -1, .msg = "missing EXPRESSION or extra '==' "},
{.state = 375, .token = -1, .msg = "missing EXPRESSION or extra '!=' "},
{.state = 378, .token = -1, .msg = "missing EXPRESSION or extra '<' "},
{.state = 376, .token = -1, .msg = "missing EXPRESSION or extra '<=' "},
{.state = 379, .token = -1, .msg = "missing EXPRESSION or extra '>' "},
{.state = 377, .token = -1, .msg = "missing EXPRESSION or extra '>=' "},
{.state = 381, .token = -1, .msg = "missing EXPRESSION or extra '>>' "},
{.state = 380, .token = -1, .msg = "missing EXPRESSION or extra '<<' "},
{.state = 386, .token = -1, .msg = "missing EXPRESSION or extra '%' "},
{.state = 399, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 188, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 406, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 737, .token = 41, .msg = "extra ',' or missing argument "},
{.state = 604, .token = 59, .msg = "missing ')' "},
{.state = 405, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 401, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 607, .token = 62, .msg = "extra space not allowed in empty instantiation "},
{.state = 408, .token = -1, .msg = "expecting '<>' or '<' TYPE_LIST '>' "},
