{.state = 149, .token = 387, .msg = "undeclared type or missing comma "},
{.state = 79, .token = 387, .msg = "type has not been declared "},
{.state = 566, .token = -1, .msg = "missing ';' "},
{.state = 367, .token = -1, .msg = "missing ')' on parameter list "},
{.state = 75, .token = -1, .msg = "expecting IDENTIFIER or '{' "},
{.state = 22, .token = -1, .msg = "expecting IDENTIFIER or '{' "},
{.state = 27, .token = -1, .msg = "expecting PATTERN "},
{.state = 29, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 30, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 41, .token = -1, .msg = "expecting '(' EXPRESSION ')' "},
{.state = 42, .token = -1, .msg = "expecting 'union' "},
{.state = 43, .token = -1, .msg = "expecting 'datatype' "},
{.state = 49, .token = -1, .msg = "expecting '((' ATTRIBUTE_LIST '))' "},
{.state = 53, .token = -1, .msg = "expecting '(' PARAMETER_LIST ')' "},
{.state = 127, .token = -1, .msg = "expecting KIND "},
{.state = 136, .token = -1, .msg = "expecting KIND "},
{.state = 63, .token = -1, .msg = "expecting ';' or '{' "},
{.state = 64, .token = -1, .msg = "expecting ';' or '{' "},
{.state = 35, .token = -1, .msg = "expecting '<' or IDENTIFIER "},
{.state = 984, .token = -1, .msg = "missing '};' "},
{.state = 78, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 108, .token = -1, .msg = "expecting '(' "},
{.state = 105, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 109, .token = -1, .msg = "expecting PATTERN "},
{.state = 261, .token = -1, .msg = "expecting IDENTIFIER or extra ',' "},
{.state = 132, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 144, .token = -1, .msg = "missing '}' "},
{.state = 312, .token = -1, .msg = "missing '}' "},
{.state = 149, .token = -1, .msg = "missing ';' "},
{.state = 317, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 315, .token = -1, .msg = "expecting DECLARATION "},
{.state = 165, .token = 0, .msg = "missing '}' "},
{.state = 169, .token = -1, .msg = "expecting ']' or EXPRESSION "},
{.state = 513, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 375, .token = -1, .msg = "expecting TYPE "},
{.state = 620, .token = -1, .msg = "missing ')' "},
{.state = 373, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 618, .token = -1, .msg = "missing ')' "},
{.state = 187, .token = -1, .msg = "expecting TYPE "},
{.state = 385, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 193, .token = -1, .msg = "missing '}' "},
{.state = 253, .token = -1, .msg = "expecting TYPE_VARIABLE or '_' "},
{.state = 194, .token = -1, .msg = "expecting '(' EXPRESSION ')' or '( TYPE ')' "},
{.state = 423, .token = -1, .msg = "missing ')' "},
{.state = 197, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 198, .token = -1, .msg = "expecting INITIALIZER or EXPRESSION "},
{.state = 200, .token = -1, .msg = "expecting '(' EXPRESSION ') "},
{.state = 398, .token = -1, .msg = "expecting EXPRESSION ') "},
{.state = 640, .token = -1, .msg = "missing ') "},
{.state = 201, .token = -1, .msg = "expecting '(' EXPRESSION ',' EXPRESSION ') "},
{.state = 399, .token = -1, .msg = "expecting EXPRESSION ',' EXPRESSION ') "},
{.state = 641, .token = -1, .msg = "expecting ',' EXPRESSION ') "},
{.state = 814, .token = -1, .msg = "missing ')' "},
{.state = 205, .token = -1, .msg = "expecting '(' "},
{.state = 403, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 645, .token = -1, .msg = "expecting ',' "},
{.state = 818, .token = -1, .msg = "expecting 'sizeof(' TYPE ')' "},
{.state = 1045, .token = -1, .msg = "expecting TYPE "},
{.state = 1188, .token = -1, .msg = "missing ')' "},
{.state = 207, .token = -1, .msg = "expecting '(' "},
{.state = 405, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 647, .token = -1, .msg = "expecting ',' "},
{.state = 820, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 939, .token = -1, .msg = "expecting ',' "},
{.state = 1047, .token = -1, .msg = "expecting 'sizeof' "},
{.state = 1123, .token = -1, .msg = "expecting '(' "},
{.state = 1190, .token = -1, .msg = "expecting TYPE "},
{.state = 1223, .token = -1, .msg = "missing ')' "},
{.state = 209, .token = -1, .msg = "expecting '(' REGION_EXPRESSION ')' "},
{.state = 649, .token = -1, .msg = "missing ')' "},
{.state = 822, .token = -1, .msg = "expecting INITIALIZER or EXPRESSION "},
{.state = 211, .token = -1, .msg = "expecting '(' EXPRESSION ')' "},
{.state = 409, .token = -1, .msg = "expecting EXPRESSION ')' "},
{.state = 651, .token = -1, .msg = "missing ')' "},
{.state = 213, .token = -1, .msg = "expecting '(' TYPE ')' "},
{.state = 411, .token = -1, .msg = "expecting TYPE ')' "},
{.state = 653, .token = -1, .msg = "missing ')' "},
{.state = 214, .token = -1, .msg = "expecting '(' "},
{.state = 412, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 654, .token = -1, .msg = "expecting '.' IDENTIFIER or missing ')' "},
{.state = 828, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 592, .token = -1, .msg = "expecting TYPE_LIST, EXPRESSION_LIST, or ')' "},
{.state = 662, .token = -1, .msg = "expecting ')' "},
{.state = 666, .token = -1, .msg = "missing ':' EXPRESSION "},
{.state = 429, .token = -1, .msg = "missing EXPRESSION or extra '?' "},
{.state = 446, .token = -1, .msg = "missing EXPRESSION or extra operator "},
{.state = 450, .token = -1, .msg = "missing EXPRESSION or extra operator "},
{.state = 431, .token = -1, .msg = "missing EXPRESSION or extra '|' "},
{.state = 433, .token = -1, .msg = "missing EXPRESSION or extra '&' "},
{.state = 432, .token = -1, .msg = "missing EXPRESSION or extra '^' "},
{.state = 226, .token = -1, .msg = "missing EXPRESSION or extra '&' "},
{.state = 436, .token = -1, .msg = "missing EXPRESSION or extra operator "},
{.state = 441, .token = -1, .msg = "missing EXPRESSION or extra operator "},
{.state = 443, .token = -1, .msg = "missing EXPRESSION or extra '>>' "},
{.state = 442, .token = -1, .msg = "missing EXPRESSION or extra '<<' "},
{.state = 463, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 217, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 470, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 836, .token = 41, .msg = "extra ',' or missing argument "},
{.state = 681, .token = 59, .msg = "missing ')' "},
{.state = 469, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 465, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 684, .token = 62, .msg = "extra space not allowed in empty instantiation "},
{.state = 472, .token = -1, .msg = "expecting '<>' or '<' TYPE_LIST '>' "},
