{.state = 129, .token = 362, .msg = "undeclared type or missing comma "},
{.state = 69, .token = 362, .msg = "type has not been declared "},
{.state = 485, .token = -1, .msg = "missing ';' "},
{.state = 314, .token = -1, .msg = "missing ')' on parameter list "},
{.state = 66, .token = -1, .msg = "expecting IDENTIFIER or '{' "},
{.state = 22, .token = -1, .msg = "expecting IDENTIFIER or '{' "},
{.state = 25, .token = -1, .msg = "expecting PATTERN "},
{.state = 27, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 28, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 36, .token = -1, .msg = "expecting '(' EXPRESSION ')' "},
{.state = 37, .token = -1, .msg = "expecting 'union' "},
{.state = 38, .token = -1, .msg = "expecting 'datatype' "},
{.state = 44, .token = -1, .msg = "expecting '((' ATTRIBUTE_LIST '))' "},
{.state = 47, .token = -1, .msg = "expecting '(' PARAMETER_LIST ')' "},
{.state = 113, .token = -1, .msg = "expecting KIND "},
{.state = 117, .token = -1, .msg = "expecting KIND "},
{.state = 55, .token = -1, .msg = "expecting ';' or '{' "},
{.state = 56, .token = -1, .msg = "expecting ';' or '{' "},
{.state = 32, .token = -1, .msg = "expecting '<' or IDENTIFIER "},
{.state = 854, .token = -1, .msg = "missing '};' "},
{.state = 68, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 93, .token = -1, .msg = "expecting '(' "},
{.state = 94, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 95, .token = -1, .msg = "expecting PATTERN "},
{.state = 227, .token = -1, .msg = "expecting IDENTIFIER or extra ',' "},
{.state = 119, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 125, .token = -1, .msg = "missing '}' "},
{.state = 264, .token = -1, .msg = "missing '}' "},
{.state = 129, .token = -1, .msg = "missing ';' "},
{.state = 267, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 266, .token = -1, .msg = "expecting DECLARATION "},
{.state = 142, .token = 0, .msg = "missing '}' "},
{.state = 149, .token = -1, .msg = "expecting ']' or EXPRESSION "},
{.state = 439, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 321, .token = -1, .msg = "expecting TYPE "},
{.state = 538, .token = -1, .msg = "missing ')' "},
{.state = 320, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 537, .token = -1, .msg = "missing ')' "},
{.state = 163, .token = -1, .msg = "expecting TYPE "},
{.state = 329, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 169, .token = -1, .msg = "missing '}' "},
{.state = 220, .token = -1, .msg = "expecting TYPE_VARIABLE or '_' "},
{.state = 170, .token = -1, .msg = "expecting '(' EXPRESSION ')' or '( TYPE ')' "},
{.state = 354, .token = -1, .msg = "missing ')' "},
{.state = 172, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 173, .token = -1, .msg = "expecting INITIALIZER or EXPRESSION "},
{.state = 174, .token = -1, .msg = "expecting '(' EXPRESSION ') "},
{.state = 339, .token = -1, .msg = "expecting EXPRESSION ') "},
{.state = 554, .token = -1, .msg = "missing ') "},
{.state = 175, .token = -1, .msg = "expecting '(' EXPRESSION ',' EXPRESSION ') "},
{.state = 340, .token = -1, .msg = "expecting EXPRESSION ',' EXPRESSION ') "},
{.state = 555, .token = -1, .msg = "expecting ',' EXPRESSION ') "},
{.state = 712, .token = -1, .msg = "missing ')' "},
{.state = 177, .token = -1, .msg = "expecting '(' "},
{.state = 342, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 557, .token = -1, .msg = "expecting ',' "},
{.state = 714, .token = -1, .msg = "expecting 'sizeof(' TYPE ')' "},
{.state = 910, .token = -1, .msg = "expecting TYPE "},
{.state = 1040, .token = -1, .msg = "missing ')' "},
{.state = 178, .token = -1, .msg = "expecting '(' "},
{.state = 343, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 558, .token = -1, .msg = "expecting ',' "},
{.state = 715, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 817, .token = -1, .msg = "expecting ',' "},
{.state = 911, .token = -1, .msg = "expecting 'sizeof' "},
{.state = 984, .token = -1, .msg = "expecting '(' "},
{.state = 1041, .token = -1, .msg = "expecting TYPE "},
{.state = 1060, .token = -1, .msg = "missing ')' "},
{.state = 179, .token = -1, .msg = "expecting '(' REGION_EXPRESSION ')' "},
{.state = 559, .token = -1, .msg = "missing ')' "},
{.state = 716, .token = -1, .msg = "expecting INITIALIZER or EXPRESSION "},
{.state = 181, .token = -1, .msg = "expecting '(' EXPRESSION ')' "},
{.state = 346, .token = -1, .msg = "expecting EXPRESSION ')' "},
{.state = 561, .token = -1, .msg = "missing ')' "},
{.state = 182, .token = -1, .msg = "expecting '(' TYPE ')' "},
{.state = 347, .token = -1, .msg = "expecting TYPE ')' "},
{.state = 562, .token = -1, .msg = "missing ')' "},
{.state = 183, .token = -1, .msg = "expecting '(' "},
{.state = 348, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 563, .token = -1, .msg = "expecting '.' IDENTIFIER or missing ')' "},
{.state = 721, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 510, .token = -1, .msg = "expecting TYPE_LIST, EXPRESSION_LIST, or ')' "},
{.state = 569, .token = -1, .msg = "expecting ')' "},
{.state = 573, .token = -1, .msg = "missing ':' EXPRESSION "},
{.state = 362, .token = -1, .msg = "missing EXPRESSION or extra '?' "},
{.state = 375, .token = -1, .msg = "missing EXPRESSION or extra '+' "},
{.state = 376, .token = -1, .msg = "missing EXPRESSION or extra '-' "},
{.state = 377, .token = -1, .msg = "missing EXPRESSION or extra '*' "},
{.state = 378, .token = -1, .msg = "missing EXPRESSION or extra '/' "},
{.state = 364, .token = -1, .msg = "missing EXPRESSION or extra '|' "},
{.state = 366, .token = -1, .msg = "missing EXPRESSION or extra '&' "},
{.state = 365, .token = -1, .msg = "missing EXPRESSION or extra '^' "},
{.state = 193, .token = -1, .msg = "missing EXPRESSION or extra '&' "},
{.state = 367, .token = -1, .msg = "missing EXPRESSION or extra '==' "},
{.state = 368, .token = -1, .msg = "missing EXPRESSION or extra '!=' "},
{.state = 371, .token = -1, .msg = "missing EXPRESSION or extra '<' "},
{.state = 369, .token = -1, .msg = "missing EXPRESSION or extra '<=' "},
{.state = 372, .token = -1, .msg = "missing EXPRESSION or extra '>' "},
{.state = 370, .token = -1, .msg = "missing EXPRESSION or extra '>=' "},
{.state = 374, .token = -1, .msg = "missing EXPRESSION or extra '>>' "},
{.state = 373, .token = -1, .msg = "missing EXPRESSION or extra '<<' "},
{.state = 379, .token = -1, .msg = "missing EXPRESSION or extra '%' "},
{.state = 392, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 184, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 399, .token = -1, .msg = "expecting EXPRESSION "},
{.state = 727, .token = 41, .msg = "extra ',' or missing argument "},
{.state = 595, .token = 59, .msg = "missing ')' "},
{.state = 398, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 394, .token = -1, .msg = "expecting IDENTIFIER "},
{.state = 598, .token = 62, .msg = "extra space not allowed in empty instantiation "},
{.state = 401, .token = -1, .msg = "expecting '<>' or '<' TYPE_LIST '>' "},
